spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: postgres
    tomcat:
      max-wait: 20000
      max-active: 50
      max-idle: 20
      min-idle: 15

  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        id:
          new_generator_mappings: false
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
